# Generated by Django 4.1 on 2022-08-20 10:28

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('structure', picklefield.fields.PickledObjectField(editable=False)),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('sequence_number', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.component')),
            ],
            options={
                'ordering': ['sequence_number'],
            },
        ),
    ]
